verison: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    envirements:
      - POSTGRES_DB=huile
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
  web:
    build: .
    command: python manage.py runserver:0.0.0.0:8000
    volumes:
      - ./code
    ports:
      - "8000:8000"
    depends_on:
      - db

