# Generated by Django 4.1.3 on 2022-11-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_type_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
