# Generated by Django 4.1.3 on 2022-11-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_fournisseur_gouvernorat_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='fournisseur',
        ),
        migrations.DeleteModel(
            name='Gouvernorat',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
