# Generated by Django 4.1.3 on 2022-12-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_gouvernorat_fournisseur_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
