# Generated by Django 4.1.3 on 2022-12-05 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_commande_code_pile_commande_dateechantion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cellage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('validé', 'Vaidé'), ('en attente', 'En Attente'), ('refusée', 'Refusée')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(default='202212051153047', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='code_pile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 5, 11, 53, 4, 430126)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='gouvernorat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.gouvernorat'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('gouvernorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.gouvernorat')),
            ],
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.ville'),
        ),
    ]
