# Generated by Django 4.1.3 on 2022-12-05 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_commande_cellage_commande_presence_commande_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code',
        ),
        migrations.AddField(
            model_name='commande',
            name='code',
            field=models.CharField(default='202212051215043', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 5, 12, 15, 4, 503738)),
        ),
    ]
