# Generated by Django 4.1.3 on 2022-12-05 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_remove_article_code_commande_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='code',
            field=models.CharField(default='202212051224553', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 5, 12, 24, 55, 405692)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('validé', 'Vaidé'), ('en attente', 'En Attente'), ('refusée', 'Refusée')], default=('en attente', 'En Attente'), max_length=100, null=True),
        ),
    ]
