# Generated by Django 4.1.3 on 2022-12-05 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0015_alter_commande_code_alter_commande_dateechantion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='code',
            field=models.CharField(default='20221205195309b', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 5, 19, 53, 9, 419111)),
        ),
    ]
