# Generated by Django 4.1.3 on 2022-12-05 19:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstApp', '0016_commande_note_alter_commande_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='degustateurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='code',
            field=models.CharField(default='20221205205250a', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 5, 20, 52, 50, 379479)),
        ),
    ]
