# Generated by Django 4.1.3 on 2022-12-13 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0017_commande_degustateurs_alter_commande_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='degustateurs',
        ),
        migrations.AlterField(
            model_name='commande',
            name='code',
            field=models.CharField(default='20221213110214a', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 13, 11, 2, 14, 337950)),
        ),
    ]
