# Generated by Django 4.1.3 on 2022-12-13 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstApp', '0018_remove_commande_degustateurs_alter_commande_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='code',
            field=models.CharField(default='202212131103092', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 13, 11, 3, 9, 635860)),
        ),
        migrations.CreateModel(
            name='DegustateursNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=200)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.commande')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='degustateurs',
            field=models.ManyToManyField(through='firstApp.DegustateursNotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
