# Generated by Django 4.1.3 on 2022-12-13 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0019_alter_commande_code_alter_commande_dateechantion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='code',
            field=models.CharField(default='20221213140008c', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateEchantion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 13, 14, 0, 8, 969228)),
        ),
        migrations.AddConstraint(
            model_name='degustateursnotes',
            constraint=models.UniqueConstraint(fields=('commande', 'user'), name='unique_user_commande_combination'),
        ),
    ]
