name: Send email on pull request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        uses: peter-evans/email-action@v1
        with:
          to: nasrimehdi96@gmail.com
          subject: New pull request opened
          body: A new pull request has been opened in the repository.
          
