name: Send email on pull request

on:
  push:
    branches: [ "main" ]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    #- name: Send mail
     
    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
        # Optional port (defaults to 465)
        port: 465
        account: ${{secrets.EMAIL_USERNAME }}
        password: ${{secrets.EMAIL_PASSWORD }}
        sender: devellany
        from: ${{secrets.EMAIL_USERNAME }}
        to: devellay@dico.me
        subject: mail title.
        body: your messages.
        # Optional content type (defaults to text/plain)
        contentType: text/plain
        # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'
