name: Send email on pull request

on:
  push:
    branches: [ "main" ]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/email@v2
        with:
          to: mehdinasri232@gmail.com
          subject: A new commit has been pushed to the repository
          body: A new commit has been pushed to the repository. Check it out at ${{ github.event.head_commit.url }}
          smtp-server: smtp.gmail.com
          smtp-port: 587
          smtp-username: nasrimehdi96@gmail.com
          smtp-password: MehdiCc24727336$
