name: Send email on pull request

on:
  push:
    branches: [ "main" ]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: Send mail
    - name: Send MAIL with gmail
      uses: thewolf25/send-email-with-gmail@v1.3
      with:
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        to: mehdinasri232@gmail.com
        subject: "test email"
        body: "My first email"
      
